from __future__ import annotations

from enum import Enum


class Intent(str, Enum):
    NEW_GOAL = "NEW_GOAL"
    STRUCTURED_GOAL = "STRUCTURED_GOAL"
    RESEARCH_REQUEST = "RESEARCH_REQUEST"
    CONTEXT_BRIEF = "CONTEXT_BRIEF"
    BUILD_TASK = "BUILD_TASK"
    ARTIFACT_BUILT = "ARTIFACT_BUILT"
    REVISION_REQUEST = "REVISION_REQUEST"
    APPROVED_OUTPUT = "APPROVED_OUTPUT"
    FINAL_REPORT = "FINAL_REPORT"
